# parser CI pipeline

trigger:
- main

pr: none

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self
  fetchDepth: 0

- template: templates/common/Setup-steps.yml

- template: templates/GenerateParser-steps.yml

- template: templates/DevelopParser-steps.yml

- template: templates/common/GitDiff-steps.yml
