name: Develop

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]
    paths:
    - 'dtdl/**'
    - 'dotnet/**'
    - 'scripts/**'
    - 'test-cases/**'
    - 'samples/**'
    - 'tutorials/**'

  push:
    branches: [ "main" ]
    paths:
    - 'dtdl/**'
    - 'dotnet/**'
    - 'scripts/**'
    - 'test-cases/**'
    - 'samples/**'
    - 'tutorials/**'

jobs:
  build:
    name: develop-main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Install WASM workload
        run: dotnet workload install wasm-tools

      - name: Install SBOM Tool
        run: dotnet tool install --global Microsoft.Sbom.DotNetTool

      - name: Build Metamodel Digest
        run: scripts/BuildMetaDigest.sh Release

      - name: Build Code Generator
        run: scripts/BuildCodeGenerator.sh Release

      - name: Build Parser Generator
        run: scripts/BuildParserGen.sh Release

      - name: Generate Parser
        run: scripts/GenerateParser.sh Release

      - name: Build Unit Test Generator
        run: scripts/BuildTestGen.sh Release

      - name: Generate ParserUnitTest
        run: scripts/GenerateParserTests.sh Release

      - name: Build Remodel Generator
        run: scripts/BuildRemodelGen.sh Release

      - name: Generate Remodel Tool
        run: scripts/GenerateRemodelTool.sh Release

      - name: Build Tutorial Extractor
        run: scripts/BuildTutorialExtractor.sh Release

      - name: Extract Tutorial Projects
        run: scripts/ExtractTutorials.sh Release

      - name: Build Parser
        run: scripts/BuildParser.sh Release

      - name: Pack Parser
        run: scripts/PackParser.sh Release

      - name: Derive Parser SBOM
        run: scripts/DeriveParserSbom.sh Release $(nbgv get-version -v SimpleVersion)

      - name: Build Parser Tests
        run: scripts/BuildParserTests.sh Release

      - name: Test Parser
        run: scripts/TestParser.sh Release

      - name: Build Remodel Tool
        run: scripts/BuildRemodelTool.sh Release

      - name: Pack Remodel Tool
        run: scripts/PackRemodelTool.sh Release

      - name: Build Parser Tutorial Projects
        run: scripts/BuildTutorials.sh Release

      - name: Test Parser Tutorial Projects
        run: scripts/TestTutorials.sh Release

      - name: Build Samples
        run: dotnet build samples/Samples.sln
