name: DTDLParser-release

on:
  create:
    branches: 
      - release/**

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'mock/Parser/Parser.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x

    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore

    - name: Install SBOM Tool
      run: dotnet tool install --global Microsoft.Sbom.DotNetTool

    - name: Derive Parser SBOM
      run: sbom-tool Generate -b mock/Parser/bin/$BUILD_CONFIG/ -bc mock/Parser -pn DTDLParser -pv $(nbgv get-version -v SimpleVersion) -ps DigitalTwinsConsortium -nsb https://www.digitaltwinconsortium.org/DTDL -m mock/Parser

    - name: Pack
      run: dotnet pack $PROJECT --configuration $BUILD_CONFIG --no-restore -p:PublicRelease=true

    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release/')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
