name: Reject Codegen Changes from Fork

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    if: github.event.pull_request.head.repo.url != github.event.pull_request.base.repo.url || !(contains(github.head_ref, '/meta-gen/') || startsWith(github.head_ref, 'meta-gen/') || startsWith(github.head_ref, 'dtdl-sync/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Remote
        run: git remote add -f DTDLParser https://github.com/digitaltwinconsortium/DTDLParser.git

      - name: Reject metamodel changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- dtdl

      - name: Reject test case changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- test-cases

      - name: Reject pipeline changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- pipelines

      - name: Reject script changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- scripts

      - name: Reject generator changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- dotnet/gen

      - name: Reject codegen Parser changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- dotnet/src/Parser/generated

      - name: Reject codegen Remodel changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- dotnet/src/Remodel/generated

      - name: Reject codegen ParserUnitTest changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- dotnet/tests/ParserUnitTest/generated

      - name: Reject codegen JavaScript changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- javascript/generated

      - name: Reject image changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- images/generated

      - name: Reject image input changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- images/input/generated

      - name: Reject tutorial project changes
        run: git diff --exit-code HEAD remotes/DTDLParser/main -- tutorials/projects
